/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.popup;

import customUI.TableCustom;
import entity.DetailTransaksi;
import entity.Transaksi;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import repository.BukuRepository;
import repository.DetailBukuHilangRepository;
import repository.KerusakanRepository;
import repository.Repository;
import static repository.Repository.conn;
import repository.TransaksiRepository;
import util.Database;
import util.ViewUtil;

/**
 *
 * @author Hafidz Fadhillah
 */
public class PopupViewDetailBukuTelahDiganti extends javax.swing.JFrame {

    private Transaksi transaksi;

    private List<DetailTransaksi> details = new ArrayList<>();
    private Integer activeDetail, totalPinjam;

    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form PopupViewDetailBuku
     */
    public PopupViewDetailBukuTelahDiganti(Transaksi transaksi) {
        this.transaksi = transaksi;
        this.details = get(new HashMap<>() {
            {
                put("transaksi.kode_transaksi", transaksi.getKode_transaksi());
            }
        });

        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));

        fillForm();
        loadTable();
        customStyleTable();

        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    private void fillForm() {
        tNamaPeminjam.setText(transaksi.getNama_peminjam());
        tKelas.setText(transaksi.getKelas());

    }

    private void loadTable() {
        int no = 1;
        int totalPinjam = 0;
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable cell editing
            }
        };

        model.addColumn("No");
        model.addColumn("Nama Buku");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Catatan");
        model.addColumn("Jumlah");
        model.addColumn("ID");

        for (DetailTransaksi detail : details) {
            int jumlahPinjam = detail.getJumlah();
            totalPinjam += jumlahPinjam;

            model.addRow(new Object[]{
                no++,
                detail.getKode_buku().getJudul_buku(),
                sdf.format(detail.getTgl_pinjam()),
                sdf.format(detail.getTgl_kembali()),
                "Klik Data",
                detail.getJumlah(),
                detail.getKode_Detailtransaksi()
            });
        }

        this.totalPinjam = totalPinjam;
        Tabel.setModel(model);
        ViewUtil.hideTableColumn(Tabel, 6);
        tJumlah.setText(String.valueOf(totalPinjam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tNamaPeminjam = new javax.swing.JTextField();
        tKelas = new javax.swing.JTextField();
        tCatatan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        tJumlah = new javax.swing.JTextField();
        btnTutup = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tNamaPeminjam.setEditable(false);
        tNamaPeminjam.setBackground(new java.awt.Color(255, 255, 255));
        tNamaPeminjam.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tNamaPeminjam.setBorder(null);
        tNamaPeminjam.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(tNamaPeminjam);
        tNamaPeminjam.setBounds(295, 184, 583, 35);

        tKelas.setEditable(false);
        tKelas.setBackground(new java.awt.Color(255, 255, 255));
        tKelas.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tKelas.setBorder(null);
        tKelas.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(tKelas);
        tKelas.setBounds(910, 184, 150, 35);

        tCatatan.setEditable(false);
        tCatatan.setBackground(new java.awt.Color(255, 255, 255));
        tCatatan.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tCatatan.setBorder(null);
        tCatatan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(tCatatan);
        tCatatan.setBounds(295, 270, 765, 67);

        Tabel.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Data", "Data", "Data"
            }
        ));
        Tabel.getTableHeader().setResizingAllowed(false);
        Tabel.getTableHeader().setReorderingAllowed(false);
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(293, 392, 770, 157);

        tJumlah.setEditable(false);
        tJumlah.setBackground(new java.awt.Color(255, 255, 255));
        tJumlah.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tJumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tJumlah.setBorder(null);
        tJumlah.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(tJumlah);
        tJumlah.setBounds(925, 575, 140, 35);

        btnTutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutupMouseClicked(evt);
            }
        });
        getContentPane().add(btnTutup);
        btnTutup.setBounds(620, 640, 130, 43);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Detail Buku Diganti.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutupMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTutupMouseClicked

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int index = Tabel.rowAtPoint(evt.getPoint());
        DetailTransaksi detail = details.get(index);
        activeDetail = index;

        tCatatan.setText(detail.getKode_buku().getCatatan());
    }//GEN-LAST:event_TabelMouseClicked

    private void customStyleTable() {
        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
    }

    public List<DetailTransaksi> get(Map<String, Object> values) {
        int iterate = 0;
        String sql = "SELECT transaksi.*, detail_transaksi.*, buku.*, kerusakan.* FROM transaksi "
                + "INNER JOIN detail_transaksi ON detail_transaksi.kode_transaksi = transaksi.kode_transaksi "
                + "INNER JOIN buku ON detail_transaksi.kode_buku = buku.kode_buku "
                + "INNER JOIN kerusakan ON detail_transaksi.kode_kerusakan = kerusakan.kode_kerusakan "
                + "WHERE buku.status = 'Diganti' AND kerusakan.jenis_kerusakan = 'Hilang' AND ";

        List<DetailTransaksi> detailTransaksis = new ArrayList<>();

        for (String valueKey : values.keySet()) {
            if (iterate > 0) {
                sql += " AND ";
            }
            sql += valueKey + " = ?";

            iterate++;
        }

        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            Database.prepareStmt(stmt, values);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                detailTransaksis.add(mapToEntity(rs));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }

        return detailTransaksis;
    }

    private DetailTransaksi mapToEntity(ResultSet result) throws SQLException {
        int bukuId = result.getInt("kode_buku");
        int kerusakanId = result.getInt("kode_kerusakan");
        int transaksiId = result.getInt("kode_transaksi");

        DetailTransaksi detailTransaksi = new DetailTransaksi(
                new BukuRepository().get(bukuId),
                result.getDate("tgl_pinjam"),
                result.getDate("tgl_kembali"),
                result.getInt("jumlah"),
                new KerusakanRepository().get(kerusakanId),
                result.getInt("nominal_denda"),
                new TransaksiRepository().get(transaksiId)
        );

        detailTransaksi.setKode_Detailtransaksi(result.getInt("kode_detail_transaksi"));
        return detailTransaksi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupViewDetailBukuTelahDiganti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupViewDetailBukuTelahDiganti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupViewDetailBukuTelahDiganti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupViewDetailBukuTelahDiganti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Transaksi transaksi = new Transaksi();
                new PopupViewDetailBukuTelahDiganti(transaksi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnTutup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tCatatan;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tKelas;
    private javax.swing.JTextField tNamaPeminjam;
    // End of variables declaration//GEN-END:variables
}
