/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.pages;

import javax.swing.ImageIcon;
import view.layouts.DaftarPetugas;
import view.layouts.ManajemenBuku;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DashboardPetugas extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardPetugas() {
        initComponents();
        
        menuAktifPertama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSideBar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        btnDaftarPetugas = new javax.swing.JLabel();
        btnPeminjaman = new javax.swing.JLabel();
        btnPengembalian = new javax.swing.JLabel();
        btnManajemen = new javax.swing.JLabel();
        btnSanksi = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        SideBar = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelSideBar.setBackground(new java.awt.Color(0,0,0,0));
        panelSideBar.setOpaque(false);
        panelSideBar.setLayout(null);

        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        panelSideBar.add(btnDashboard);
        btnDashboard.setBounds(23, 117, 294, 50);

        btnDaftarPetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftarPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarPetugasMouseClicked(evt);
            }
        });
        panelSideBar.add(btnDaftarPetugas);
        btnDaftarPetugas.setBounds(23, 197, 294, 50);

        btnPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseClicked(evt);
            }
        });
        panelSideBar.add(btnPeminjaman);
        btnPeminjaman.setBounds(23, 277, 294, 50);

        btnPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseClicked(evt);
            }
        });
        panelSideBar.add(btnPengembalian);
        btnPengembalian.setBounds(23, 357, 294, 50);

        btnManajemen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManajemenMouseClicked(evt);
            }
        });
        panelSideBar.add(btnManajemen);
        btnManajemen.setBounds(23, 437, 294, 50);

        btnSanksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSanksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanksiMouseClicked(evt);
            }
        });
        panelSideBar.add(btnSanksi);
        btnSanksi.setBounds(23, 517, 294, 50);

        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
        });
        panelSideBar.add(btnLaporan);
        btnLaporan.setBounds(23, 597, 294, 50);

        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        panelSideBar.add(btnLogout);
        btnLogout.setBounds(23, 677, 294, 50);

        SideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Sidebar.png"))); // NOI18N
        panelSideBar.add(SideBar);
        SideBar.setBounds(0, 0, 352, 777);

        getContentPane().add(panelSideBar);
        panelSideBar.setBounds(0, 0, 350, 768);

        jDesktopPane1.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        btnDashboard.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Dashboard.png")));
        btnDaftarPetugas.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnPengembalian.setIcon(null);
        btnManajemen.setIcon(null);
        btnSanksi.setIcon(null);
        btnLaporan.setIcon(null);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDaftarPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPetugasMouseClicked
        // TODO add your handling code here:
        btnDaftarPetugas.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Petugas.png")));
        btnDashboard.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnPengembalian.setIcon(null);
        btnManajemen.setIcon(null);
        btnSanksi.setIcon(null);
        btnLaporan.setIcon(null);
        
        jDesktopPane1.removeAll();
        DaftarPetugas tb = new DaftarPetugas();
        jDesktopPane1.add(tb).setVisible(true);
    }//GEN-LAST:event_btnDaftarPetugasMouseClicked

    private void btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseClicked
        // TODO add your handling code here:
        btnPeminjaman.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Peminjaman.png")));
        btnDashboard.setIcon(null);
        btnDaftarPetugas.setIcon(null);
        btnPengembalian.setIcon(null);
        btnManajemen.setIcon(null);
        btnSanksi.setIcon(null);
        btnLaporan.setIcon(null);
    }//GEN-LAST:event_btnPeminjamanMouseClicked

    private void btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseClicked
        // TODO add your handling code here:
        btnPengembalian.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Pengembalian.png")));
        btnDashboard.setIcon(null);
        btnDaftarPetugas.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnManajemen.setIcon(null);
        btnSanksi.setIcon(null);
        btnLaporan.setIcon(null);
    }//GEN-LAST:event_btnPengembalianMouseClicked

    private void btnManajemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenMouseClicked
        // TODO add your handling code here:
        btnManajemen.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Manajemen.png")));
        btnDashboard.setIcon(null);
        btnDaftarPetugas.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnPengembalian.setIcon(null);
        btnSanksi.setIcon(null);
        btnLaporan.setIcon(null);
        
        jDesktopPane1.removeAll();
        ManajemenBuku mb = new ManajemenBuku();
        jDesktopPane1.add(mb).setVisible(true);
    }//GEN-LAST:event_btnManajemenMouseClicked

    private void btnSanksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanksiMouseClicked
        // TODO add your handling code here:
        btnSanksi.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Sanksi.png")));
        btnDashboard.setIcon(null);
        btnDaftarPetugas.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnPengembalian.setIcon(null);
        btnManajemen.setIcon(null);
        btnLaporan.setIcon(null);
    }//GEN-LAST:event_btnSanksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        // TODO add your handling code here:
        btnLaporan.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Laporan.png")));
        btnDashboard.setIcon(null);
        btnDaftarPetugas.setIcon(null);
        btnPeminjaman.setIcon(null);
        btnPengembalian.setIcon(null);
        btnManajemen.setIcon(null);
        btnSanksi.setIcon(null);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPetugas().setVisible(true);
            }
        });
    }
    
    private void menuAktifPertama() {
       btnDashboard.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Dashboard.png")));
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SideBar;
    private javax.swing.JLabel btnDaftarPetugas;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLaporan;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnManajemen;
    private javax.swing.JLabel btnPeminjaman;
    private javax.swing.JLabel btnPengembalian;
    private javax.swing.JLabel btnSanksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel panelSideBar;
    // End of variables declaration//GEN-END:variables
}
