/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.pages;

import javax.swing.ImageIcon;
import view.layouts.DaftarBukuSiswa;
import view.layouts.TambahPinjamanSiswa;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DashboardSiswa extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardSiswa() {
        initComponents();

        menuAktifPertama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSideBar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        btnDaftarBuku = new javax.swing.JLabel();
        btnPinjamBuku = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        SideBar = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelSideBar.setBackground(new java.awt.Color(0,0,0,0));
        panelSideBar.setOpaque(false);
        panelSideBar.setLayout(null);

        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        panelSideBar.add(btnDashboard);
        btnDashboard.setBounds(26, 111, 294, 50);

        btnDaftarBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftarBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarBukuMouseClicked(evt);
            }
        });
        panelSideBar.add(btnDaftarBuku);
        btnDaftarBuku.setBounds(25, 191, 294, 50);

        btnPinjamBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPinjamBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPinjamBukuMouseClicked(evt);
            }
        });
        panelSideBar.add(btnPinjamBuku);
        btnPinjamBuku.setBounds(25, 271, 294, 50);

        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        panelSideBar.add(btnLogout);
        btnLogout.setBounds(23, 677, 294, 50);

        SideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Sidebar Siswa.png"))); // NOI18N
        panelSideBar.add(SideBar);
        SideBar.setBounds(0, 0, 343, 768);

        getContentPane().add(panelSideBar);
        panelSideBar.setBounds(0, 0, 350, 768);

        jDesktopPane1.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        btnDashboard.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Dashboard.png")));
        btnDaftarBuku.setIcon(null);
        btnPinjamBuku.setIcon(null);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDaftarBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarBukuMouseClicked
        // TODO add your handling code here:
        btnDaftarBuku.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Daftar Buku.png")));
        btnDashboard.setIcon(null);
        btnPinjamBuku.setIcon(null);

        jDesktopPane1.removeAll();
        DaftarBukuSiswa dbs = new DaftarBukuSiswa();
        jDesktopPane1.add(dbs).setVisible(true);
    }//GEN-LAST:event_btnDaftarBukuMouseClicked

    private void btnPinjamBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinjamBukuMouseClicked
        // TODO add your handling code here:
        btnPinjamBuku.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Pinjam Buku.png")));
        btnDashboard.setIcon(null);
        btnDaftarBuku.setIcon(null);

        jDesktopPane1.removeAll();
        TambahPinjamanSiswa tps = new TambahPinjamanSiswa();
        jDesktopPane1.add(tps).setVisible(true);
    }//GEN-LAST:event_btnPinjamBukuMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardSiswa().setVisible(true);
            }
        });
    }

    private void menuAktifPertama() {
        btnDashboard.setIcon(new ImageIcon(getClass().getResource("/assets/layouts/Menu Dashboard.png")));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SideBar;
    private javax.swing.JLabel btnDaftarBuku;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPinjamBuku;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel panelSideBar;
    // End of variables declaration//GEN-END:variables
}
