/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.pages;

import data.SessionData;
import entity.Petugas;
import jakarta.validation.ConstraintViolation;
import java.util.Set;
import javax.swing.JOptionPane;
import service.AuthService;
import util.ValidasiUtil;
import view.popup.PopupViewDataPasswordTidakSama;
import view.popup.PopupViewPasswordBerhasilDiubah;

/**
 *
 * @author Hafidz Fadhillah
 */
public class PasswordBaruView extends javax.swing.JFrame {

    /**
     * Creates new form PasswordBaruView
     */
    public PasswordBaruView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        tPassBaru = new javax.swing.JPasswordField();
        tPassKonf = new javax.swing.JPasswordField();
        CheckBox = new javax.swing.JCheckBox();
        btnSimpan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(296, 167, 54, 50);

        tPassBaru.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        tPassBaru.setBorder(null);
        getContentPane().add(tPassBaru);
        tPassBaru.setBounds(345, 344, 373, 45);

        tPassKonf.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        tPassKonf.setBorder(null);
        getContentPane().add(tPassKonf);
        tPassKonf.setBounds(345, 453, 373, 45);

        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox);
        CheckBox.setBounds(335, 514, 20, 20);

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(463, 550, 116, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Ganti Password.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1080, 763);

        setSize(new java.awt.Dimension(1080, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        // TODO add your handling code here:
        if (CheckBox.isSelected()) {
           tPassBaru.setEchoChar((char)0);
           tPassKonf.setEchoChar((char)0);
        } else {
           tPassBaru.setEchoChar('\u2022');
           tPassKonf.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new CodeOTPView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        Petugas petugas = SessionData.petugas;
        
        if (tPassBaru.getText().equals(tPassKonf.getText())) {
            petugas.setPassword(tPassBaru.getText());
            
            Set<ConstraintViolation<Petugas>> violations = ValidasiUtil.validate(petugas);
            String errors = ValidasiUtil.getErrorsAsString(violations, "\n");
            
            if (violations.size() > 0) {
                JOptionPane.showMessageDialog(this, errors);
            } else {
                new AuthService().resetPassword(petugas);
                
                new PopupViewPasswordBerhasilDiubah().setVisible(true);
                this.dispose();
            }
        } else {
            new PopupViewDataPasswordTidakSama().setVisible(true);
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordBaruView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordBaruView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordBaruView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordBaruView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordBaruView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JPasswordField tPassBaru;
    private javax.swing.JPasswordField tPassKonf;
    // End of variables declaration//GEN-END:variables
}
