/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import customUI.TableCustom;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import entity.Klasifikasi;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import repository.KlasifikasiRepository;
import repository.Repository;
import util.ViewUtil;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DaftarKlasifikasi extends javax.swing.JInternalFrame {
    private Repository<Klasifikasi> klsfRepo = new KlasifikasiRepository();
    
    /**
     * Creates new form TambahKlasifikasi
     */
    public DaftarKlasifikasi() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);
        
        jam();
        loadDataTable(klsfRepo.get());
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        btnManajemenBuku = new javax.swing.JLabel();
        btnKlasifikasi = new javax.swing.JLabel();
        btnPenerbit = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        btnManajemenBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemenBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManajemenBukuMouseClicked(evt);
            }
        });
        getContentPane().add(btnManajemenBuku);
        btnManajemenBuku.setBounds(433, 150, 105, 33);

        btnKlasifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKlasifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKlasifikasiMouseClicked(evt);
            }
        });
        getContentPane().add(btnKlasifikasi);
        btnKlasifikasi.setBounds(562, 150, 145, 33);

        btnPenerbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenerbitMouseClicked(evt);
            }
        });
        getContentPane().add(btnPenerbit);
        btnPenerbit.setBounds(732, 150, 102, 33);

        tCari.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tCari.setBorder(null);
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(988, 147, 280, 40);

        Tabel.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Data", "Data", "Data"
            }
        ));
        Tabel.getTableHeader().setReorderingAllowed(false);
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(437, 210, 863, 495);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Daftar Klasifikasi.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        String value = tCari.getText();
        List<Klasifikasi> klasifikasis = klsfRepo.search(new HashMap<>() {{
            put("kode_ddc", value);
            put("nama_klasifikasi", value);
        }});
        
        loadDataTable(klasifikasis);
    }//GEN-LAST:event_tCariKeyReleased

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int row = Tabel.getSelectedRow();
        String value = Tabel.getModel().getValueAt(row, 3).toString();
        Klasifikasi klasifikasi = klsfRepo.get(Integer.valueOf(value));
        
        EditKlasifikasi editKlasifikasi = new EditKlasifikasi(klasifikasi);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(editKlasifikasi);
        editKlasifikasi.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TabelMouseClicked

    private void btnManajemenBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenBukuMouseClicked
        // TODO add your handling code here:
        ManajemenBuku manajemenKlasifikasi = new ManajemenBuku();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(manajemenKlasifikasi);
        manajemenKlasifikasi.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnManajemenBukuMouseClicked

    private void btnKlasifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKlasifikasiMouseClicked
        // TODO add your handling code here:
        TambahKlasifikasi tambahKlasifikasi = new TambahKlasifikasi();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(tambahKlasifikasi);
        tambahKlasifikasi.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnKlasifikasiMouseClicked

    private void btnPenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenerbitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPenerbitMouseClicked

    private void loadDataTable(List<Klasifikasi> klasifikasis) {
        int no = 1;
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable cell editing
            }
        };
        
        model.addColumn("No");
        model.addColumn("Kode DDC");
        model.addColumn("Nama Klasifikasi");
        model.addColumn("ID");
        
        for (Klasifikasi klasifikasi: klasifikasis) {
            
            model.addRow(new Object[] {
                no++,
                klasifikasi.getKode_ddc(),
                klasifikasi.getNama_klasifikasi(),
                klasifikasi.getId_klasifikasi(),
            });
        }
        
        Tabel.setModel(model);
        ViewUtil.hideTableColumn(Tabel, 3);
        customStyleTable();
    }
    
    private void customStyleTable() {        
        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
    }
    
    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();
                    
                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);
                    
                    if (jam < 10) {
                        noljam = "0";
                    }
                    
                    if (menit < 10) {
                        nolmenit = "0";
                    }
                    
                    if (detik < 10) {
                        noldetik = "0";
                    }
                    
                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;
                    
                    tJam.setText(finalJam);
            }};
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnKlasifikasi;
    private javax.swing.JLabel btnManajemenBuku;
    private javax.swing.JLabel btnPenerbit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tCari;
    private javax.swing.JLabel tJam;
    // End of variables declaration//GEN-END:variables
}
