/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.HashMap;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import entity.Petugas;
import javax.swing.JDesktopPane;
import repository.Repository;
import repository.PetugasRepository;
import customUI.TableCustom;
import java.awt.Color;
import util.ViewUtil;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DaftarLaporan extends javax.swing.JInternalFrame {

    private String username;

//    private Repository<Petugas> ptgRepo = new PetugasRepository();
//    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form TambahBuku
     */
    public DaftarLaporan() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);

        jam();
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    public void setUsername(String username) {
        this.username = username;

        if (username != null) {
            username = username.trim();
            // Split the username into words
            String[] words = username.split("\\s+");
            // Get the first word
            String firstWord = words[0];
            // Capitalize the first letter of the first word
            String capitalizedFirstWord = firstWord.substring(0, 1).toUpperCase() + firstWord.substring(1);
            tUserLogin.setText("Selamat Datang " + capitalizedFirstWord + " !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        btnCetak = new javax.swing.JLabel();
        dropDownData = new javax.swing.JComboBox<>();
        dropDownData1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);
        getContentPane().add(btnCetak);
        btnCetak.setBounds(1157, 143, 173, 33);

        dropDownData.setBackground(new Color(0,0,0,0)
        );
        dropDownData.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        dropDownData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peminjaman", "Pengembalian", "Sanksi" }));
        dropDownData.setSelectedIndex(-1);
        dropDownData.setBorder(null);
        getContentPane().add(dropDownData);
        dropDownData.setBounds(490, 145, 165, 31);

        dropDownData1.setBackground(new Color(0,0,0,0)
        );
        dropDownData1.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        dropDownData1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli ", "Agustus", "September", "Oktober", "November", "Desember" }));
        dropDownData1.setSelectedIndex(-1);
        dropDownData1.setBorder(null);
        getContentPane().add(dropDownData1);
        dropDownData1.setBounds(743, 145, 145, 31);

        Tabel.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Data", "Data", "Data"
            }
        ));
        Tabel.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(437, 195, 890, 510);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Laporan.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

//    private void loadDataTable(List<Petugas> petugass) {
//        int no = 1;
//        DefaultTableModel model = new DefaultTableModel() {
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false; // Disable cell editing
//            }
//        };
//
//        model.addColumn("No");
//        model.addColumn("Nama");
//        model.addColumn("Email");
//        model.addColumn("Username");
//        model.addColumn("Tanggal Lahir");
//        model.addColumn("ID");
//
//        for (Petugas petugas : petugass) {
//
//            model.addRow(new Object[]{
//                no++,
//                petugas.getNama(),
//                petugas.getEmail(),
//                petugas.getUsername(),
//                sdf.format(petugas.getTgl_lahir()),
//                petugas.getId()
//            });
//        }
//
//        Tabel.setModel(model);
//        ViewUtil.hideTableColumn(Tabel, 5);
//        customStyleTable();
//    }
//
//    private void customStyleTable() {
//        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
//    }
    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();

                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);

                    if (jam < 10) {
                        noljam = "0";
                    }

                    if (menit < 10) {
                        nolmenit = "0";
                    }

                    if (detik < 10) {
                        noldetik = "0";
                    }

                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;

                    tJam.setText(finalJam);
                }
            };
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnCetak;
    private javax.swing.JComboBox<String> dropDownData;
    private javax.swing.JComboBox<String> dropDownData1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tJam;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
