/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import customUI.TableCustom;
import data.BukuStatus;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import entity.Buku;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JDesktopPane;

import repository.BukuRepository;
import repository.Repository;
import static repository.Repository.conn;
import util.ViewUtil;
import view.popup.PopupViewDetailBuku;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DaftarStatusBuku extends javax.swing.JInternalFrame {

    private String username;

    private Repository<Buku> bkuRepo = new BukuRepository();

    /**
     * Creates new form TambahBuku
     */
    public DaftarStatusBuku() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);

        loadDataTable(bkuRepo.get());
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    public void setUsername(String username) {
        this.username = username;

        if (username != null) {
            username = username.trim();
            // Split the username into words
            String[] words = username.split("\\s+");
            // Get the first word
            String firstWord = words[0];
            // Capitalize the first letter of the first word
            String capitalizedFirstWord = firstWord.substring(0, 1).toUpperCase() + firstWord.substring(1);
            tUserLogin.setText("Selamat Datang " + capitalizedFirstWord + " !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        btnManajemenBuku = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        tStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        btnManajemenBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemenBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManajemenBukuMouseClicked(evt);
            }
        });
        getContentPane().add(btnManajemenBuku);
        btnManajemenBuku.setBounds(447, 150, 156, 30);

        tCari.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tCari.setBorder(null);
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(983, 145, 280, 40);

        tStatus.setBackground(new Color(0,0,0,0));
        tStatus.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Layak", "Dipinjam", "Rusak", "Hilang" }));
        tStatus.setSelectedIndex(-1);
        tStatus.setBorder(null);
        getContentPane().add(tStatus);
        tStatus.setBounds(530, 203, 225, 35);

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(775, 205, 68, 32);

        Tabel.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Data", "Data", "Data"
            }
        ));
        Tabel.getTableHeader().setReorderingAllowed(false);
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(437, 265, 883, 440);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Status Buku.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        String value = tCari.getText();
        List<Buku> bukus = bkuRepo.search(new HashMap<>() {
            {
                put("isbn", value);
                put("judul_buku", value);
                put("nama_pengarang", value);
            }
        });

        loadDataTable(bukus);
    }//GEN-LAST:event_tCariKeyReleased

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int row = Tabel.getSelectedRow();
        String value = Tabel.getModel().getValueAt(row, 8).toString();
        Buku buku = bkuRepo.get(Integer.valueOf(value));

        new PopupViewDetailBuku(buku).setVisible(true);
    }//GEN-LAST:event_TabelMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        String value = tStatus.getSelectedItem().toString();

        String sql = "SELECT * FROM buku WHERE status = ?";

        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setString(1, value);
            ResultSet results = statement.executeQuery();

            List<Buku> bukuList = new ArrayList<>();

            while (results.next()) {
                Buku buku = new Buku();

                buku.setIsbn(results.getInt("isbn"));
                buku.setJudul_buku(results.getString("judul_buku"));
                buku.setNama_pengarang(results.getString("nama_pengarang"));
                buku.setSumber(results.getString("sumber"));
                buku.setHalaman(results.getInt("halaman"));
                buku.setBukuStatus(BukuStatus.valueOf(results.getString("status")));
                buku.setJumlah(results.getInt("jumlah"));
                buku.setKode_buku(results.getInt("kode_buku"));

                bukuList.add(buku); // Add the buku object to the list
            }
            loadDataTable(bukuList);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnManajemenBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenBukuMouseClicked
        // TODO add your handling code here:
        ManajemenBuku manajemenKlasifikasi = new ManajemenBuku();
        manajemenKlasifikasi.setUsername(username);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(manajemenKlasifikasi);
        manajemenKlasifikasi.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnManajemenBukuMouseClicked

    private void loadDataTable(List<Buku> bukus) {
        int no = 1;
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable cell editing
            }
        };

        model.addColumn("No");
        model.addColumn("ISBN");
        model.addColumn("Judul Buku");
        model.addColumn("Nama Pengarang");
        model.addColumn("Sumber");
        model.addColumn("Halaman");
        model.addColumn("Status");
        model.addColumn("Jumlah");
        model.addColumn("ID");

        for (Buku buku : bukus) {

            model.addRow(new Object[]{
                no++,
                buku.getIsbn(),
                buku.getJudul_buku(),
                buku.getNama_pengarang(),
                buku.getSumber(),
                buku.getHalaman(),
                buku.getBukuStatus(),
                buku.getJumlah(),
                buku.getKode_buku()
            });
        }

        Tabel.setModel(model);
        ViewUtil.hideTableColumn(Tabel, 8);
        customStyleTable();
    }

    private void customStyleTable() {
        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
    }

    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();

                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);

                    if (jam < 10) {
                        noljam = "0";
                    }

                    if (menit < 10) {
                        nolmenit = "0";
                    }

                    if (detik < 10) {
                        noldetik = "0";
                    }

                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;

                    tJam.setText(finalJam);
                }
            };
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnManajemenBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tCari;
    private javax.swing.JLabel tJam;
    private javax.swing.JComboBox<String> tStatus;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
