/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import data.ChartData;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import raven.chart.ModelChart;
import repository.DashboardPRespository;
import util.NumberFormatUtil;

/**
 *
 * @author Hafidz Fadhillah
 */
public class DashboardPetugasView extends javax.swing.JInternalFrame {

    private String username;

    private DashboardPRespository repo = new DashboardPRespository();

    /**
     * Creates new form TambahBuku
     */
    public DashboardPetugasView() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);

        initChart();
        fillDashboard();

        jam();
    }

    public void setUsername(String username) {
        this.username = username;

        if (username != null) {
            username = username.trim();
            // Split the username into words
            String[] words = username.split("\\s+");
            // Get the first word
            String firstWord = words[0];
            // Capitalize the first letter of the first word
            String capitalizedFirstWord = firstWord.substring(0, 1).toUpperCase() + firstWord.substring(1);
            tUserLogin.setText("Selamat Datang " + capitalizedFirstWord + " !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        tPetugas = new javax.swing.JLabel();
        tBukuDipinjam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tBukuBelumKembali = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tTotalBuku = new javax.swing.JLabel();
        chart = new raven.chart.CurveLineChart();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        tPetugas.setFont(new java.awt.Font("Calisto MT", 0, 90)); // NOI18N
        tPetugas.setForeground(new java.awt.Color(51, 51, 51));
        tPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tPetugas);
        tPetugas.setBounds(470, 200, 140, 120);

        tBukuDipinjam.setFont(new java.awt.Font("Calisto MT", 0, 90)); // NOI18N
        tBukuDipinjam.setForeground(new java.awt.Color(51, 51, 51));
        tBukuDipinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tBukuDipinjam);
        tBukuDipinjam.setBounds(693, 200, 140, 120);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel1.setText("Bulan Ini");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(800, 330, 60, 17);

        tBukuBelumKembali.setFont(new java.awt.Font("Calisto MT", 0, 90)); // NOI18N
        tBukuBelumKembali.setForeground(new java.awt.Color(51, 51, 51));
        tBukuBelumKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tBukuBelumKembali);
        tBukuBelumKembali.setBounds(917, 200, 140, 120);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setText("Bulan Ini");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1020, 330, 60, 17);

        tTotalBuku.setFont(new java.awt.Font("Calisto MT", 0, 90)); // NOI18N
        tTotalBuku.setForeground(new java.awt.Color(51, 51, 51));
        tTotalBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tTotalBuku);
        tTotalBuku.setBounds(1143, 200, 140, 120);

        chart.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(chart);
        chart.setBounds(450, 420, 850, 310);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Dashboard Petugas.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void fillDashboard() {
        tPetugas.setText(NumberFormatUtil.formatDec(repo.getTotalPetugas()));
        tBukuDipinjam.setText(NumberFormatUtil.formatDec(repo.getBukuDipinjam(new Date())));
        tBukuBelumKembali.setText(NumberFormatUtil.formatDec(repo.getBukuBelumKembali(new Date())));
        tTotalBuku.setText(NumberFormatUtil.formatDec(repo.getTotalBuku()));
    }

    private void initChart() {
        List<ChartData> cData = repo.getChartData();

        chart.addLegend("Buku Dipinjam", Color.decode("#7b4397"), Color.decode("#dc2430"));
        chart.addLegend("Peminjam", Color.decode("#0099F7"), Color.decode("#F11712"));

        for (ChartData data : cData) {
            chart.addData(new ModelChart(data.getMonth(), new double[]{
                data.getBuku(),
                data.getPeminjam()
            }));
        }

        if (cData.size() > 1) {
            chart.start();
        }
    }

    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();

                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);

                    if (jam < 10) {
                        noljam = "0";
                    }

                    if (menit < 10) {
                        nolmenit = "0";
                    }

                    if (detik < 10) {
                        noldetik = "0";
                    }

                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;

                    tJam.setText(finalJam);
                }
            };
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private raven.chart.CurveLineChart chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tBukuBelumKembali;
    private javax.swing.JLabel tBukuDipinjam;
    private javax.swing.JLabel tJam;
    private javax.swing.JLabel tPetugas;
    private javax.swing.JLabel tTotalBuku;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
