/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import jakarta.validation.ConstraintViolation;

import entity.Kerusakan;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import util.ValidasiUtil;
import repository.Repository;
import repository.KerusakanRepository;
import view.popup.PopupViewDataDiubah;
import view.popup.PopupViewHapusData;

/**
 *
 * @author Hafidz Fadhillah
 */
public class EditKerusakan extends javax.swing.JInternalFrame {

    private Kerusakan sanksi;
    private String username;

    private Repository<Kerusakan> snksRepo = new KerusakanRepository();

    /**
     * Creates new form TambahSanksi
     */
    public EditKerusakan(Kerusakan sanksi) {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);

        this.sanksi = sanksi;

        fillForm();

        jam();
    }

    public void setUsername(String username) {
        this.username = username;

        if (username != null) {
            username = username.trim();
            // Split the username into words
            String[] words = username.split("\\s+");
            // Get the first word
            String firstWord = words[0];
            // Capitalize the first letter of the first word
            String capitalizedFirstWord = firstWord.substring(0, 1).toUpperCase() + firstWord.substring(1);
            tUserLogin.setText("Selamat Datang " + capitalizedFirstWord + " !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        tJenisDenda = new javax.swing.JTextField();
        tNominalDenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDeskripsiDenda = new javax.swing.JTextArea();
        btnHapus = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        tJenisDenda.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tJenisDenda.setBorder(null);
        getContentPane().add(tJenisDenda);
        tJenisDenda.setBounds(438, 178, 423, 35);

        tNominalDenda.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tNominalDenda.setBorder(null);
        tNominalDenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNominalDendaKeyPressed(evt);
            }
        });
        getContentPane().add(tNominalDenda);
        tNominalDenda.setBounds(897, 178, 423, 35);

        jScrollPane1.setBorder(null);

        tDeskripsiDenda.setColumns(20);
        tDeskripsiDenda.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tDeskripsiDenda.setRows(5);
        jScrollPane1.setViewportView(tDeskripsiDenda);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 259, 880, 186);

        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(429, 470, 144, 40);

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(1185, 470, 145, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Edit Kerusakan.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        sanksi.setJenis_kerusakan(tJenisDenda.getText());
        sanksi.setDeskripsi_kerusakan(tDeskripsiDenda.getText());
        sanksi.setNominal_denda(Integer.valueOf(tNominalDenda.getText()));

        Set<ConstraintViolation<Kerusakan>> vols = ValidasiUtil.validate(sanksi);

        try {
            snksRepo.update(sanksi);

            DaftarKerusakan daftarKerusakan = new DaftarKerusakan();
            daftarKerusakan.setUsername(username);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(daftarKerusakan);
            daftarKerusakan.setVisible(true);

            this.dispose();

            new PopupViewDataDiubah().setVisible(true);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        int clicked = JOptionPane.showOptionDialog(
                this, // Parent component
                "Apakah Anda yakin ?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Ya", "Tidak"},
                "Tidak"
        );

        if (clicked == JOptionPane.YES_OPTION) {
            snksRepo.delete(sanksi.getKode_kerusakan());

            DaftarKerusakan daftarKerusakan = new DaftarKerusakan();
            daftarKerusakan.setUsername(username);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(daftarKerusakan);
            daftarKerusakan.setVisible(true);

            this.dispose();

            new PopupViewHapusData().setVisible(true);
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void tNominalDendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNominalDendaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            tNominalDenda.setEditable(false);
        } else {
            tNominalDenda.setEditable(true);
        }
    }//GEN-LAST:event_tNominalDendaKeyPressed

    private void fillForm() {
        tJenisDenda.setText(sanksi.getJenis_kerusakan());
        tDeskripsiDenda.setText(sanksi.getDeskripsi_kerusakan());
        tNominalDenda.setText(String.valueOf(sanksi.getNominal_denda()));
    }

    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();

                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);

                    if (jam < 10) {
                        noljam = "0";
                    }

                    if (menit < 10) {
                        nolmenit = "0";
                    }

                    if (detik < 10) {
                        noldetik = "0";
                    }

                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;

                    tJam.setText(finalJam);
                }
            };
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tDeskripsiDenda;
    private javax.swing.JLabel tJam;
    private javax.swing.JTextField tJenisDenda;
    private javax.swing.JTextField tNominalDenda;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
