/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import customUI.TableCustom;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import entity.Buku;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import repository.BukuRepository;
import repository.Repository;
import util.ViewUtil;
import view.popup.PopupViewDetailBuku;

/**
 *
 * @author Hafidz Fadhillah
 */
public class ManajemenBuku extends javax.swing.JInternalFrame {
    private String username;
    
    private Repository<Buku> bkuRepo = new BukuRepository();
    
    /**
     * Creates new form TambahBuku
     */
    public ManajemenBuku() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);
        
        jam();
        loadDataTable(bkuRepo.get());
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    public void setUsername(String username) {
        this.username = username;
        String result = username.substring(0, 1).toUpperCase() + username.substring(1);
        tUserLogin.setText("Selamat Datang " + result + " !");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        btnTambahBuku = new javax.swing.JLabel();
        btnKlasifikasi = new javax.swing.JLabel();
        btnPenerbit = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        btnTambahBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahBukuMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambahBuku);
        btnTambahBuku.setBounds(433, 150, 150, 33);

        btnKlasifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKlasifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKlasifikasiMouseClicked(evt);
            }
        });
        getContentPane().add(btnKlasifikasi);
        btnKlasifikasi.setBounds(605, 150, 102, 33);

        btnPenerbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenerbitMouseClicked(evt);
            }
        });
        getContentPane().add(btnPenerbit);
        btnPenerbit.setBounds(732, 150, 102, 33);

        tCari.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tCari.setBorder(null);
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(988, 147, 280, 40);

        Tabel.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Data", "Data", "Data"
            }
        ));
        Tabel.getTableHeader().setReorderingAllowed(false);
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(437, 210, 863, 495);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Management Buku.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        String value = tCari.getText();
        List<Buku> bukus = bkuRepo.search(new HashMap<>() {{
            put("isbn", value);
            put("judul_buku", value);
            put("nama_pengarang", value);
        }});
        
        loadDataTable(bukus);
    }//GEN-LAST:event_tCariKeyReleased

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int row = Tabel.getSelectedRow();
        String value = Tabel.getModel().getValueAt(row, 7).toString();
        Buku buku = bkuRepo.get(Integer.valueOf(value));
        
        int choice = JOptionPane.showOptionDialog(
            this, 
            "Pilih Opsi Yang Akan Anda Lakukan!",
            "Konfirmasi", 
            JOptionPane.DEFAULT_OPTION, 
            JOptionPane.QUESTION_MESSAGE, 
            null, 
            new Object[]{"Detail", "Edit", "Cancel"}, 
            "Detail" 
        );

        if (choice == 0) {
            new PopupViewDetailBuku(buku).setVisible(true);
        } else if (choice == 1) {
            EditBuku editBuku = new EditBuku(buku);
            editBuku.setUsername(username);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(editBuku);
            editBuku.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_TabelMouseClicked

    private void btnTambahBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBukuMouseClicked
        // TODO add your handling code here:
        TambahBuku tambahBuku = new TambahBuku();
        tambahBuku.setUsername(username);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(tambahBuku);
        tambahBuku.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnTambahBukuMouseClicked

    private void btnKlasifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKlasifikasiMouseClicked
        // TODO add your handling code here:
        DaftarKlasifikasi daftarKlasifikasi = new DaftarKlasifikasi();
        daftarKlasifikasi.setUsername(username);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(daftarKlasifikasi);
        daftarKlasifikasi.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnKlasifikasiMouseClicked

    private void btnPenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenerbitMouseClicked
        // TODO add your handling code here:
        DaftarPenerbit daftarPenerbit = new DaftarPenerbit();
        daftarPenerbit.setUsername(username);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(daftarPenerbit);
        daftarPenerbit.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnPenerbitMouseClicked

    private void loadDataTable(List<Buku> bukus) {
        int no = 1;
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable cell editing
            }
        };
        
        model.addColumn("No");
        model.addColumn("ISBN");
        model.addColumn("Judul Buku");
        model.addColumn("Nama Pengarang");
        model.addColumn("Sumber");
        model.addColumn("Halaman");
        model.addColumn("Jumlah");
        model.addColumn("ID");
        
        for (Buku buku: bukus) {
            
            model.addRow(new Object[] {
                no++,
                buku.getIsbn(),
                buku.getJudul_buku(),
                buku.getNama_pengarang(),
                buku.getSumber(),
                buku.getHalaman(),
                buku.getJumlah(),
                buku.getKode_buku()
            });
        }
        
        Tabel.setModel(model);
        ViewUtil.hideTableColumn(Tabel, 7);
        customStyleTable();
    }
    
    private void customStyleTable() {        
        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
    }
    
    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();
                    
                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);
                    
                    if (jam < 10) {
                        noljam = "0";
                    }
                    
                    if (menit < 10) {
                        nolmenit = "0";
                    }
                    
                    if (detik < 10) {
                        noldetik = "0";
                    }
                    
                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;
                    
                    tJam.setText(finalJam);
            }};
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnKlasifikasi;
    private javax.swing.JLabel btnPenerbit;
    private javax.swing.JLabel btnTambahBuku;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tCari;
    private javax.swing.JLabel tJam;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
