/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import jakarta.validation.ConstraintViolation;

import entity.Petugas;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import util.ValidasiUtil;
import repository.Repository;
import repository.PetugasRepository;
import view.popup.PopupViewDataBerhasil;
import view.popup.PopupViewDataGagal;

/**
 *
 * @author Hafidz Fadhillah
 */
public class TambahPetugas extends javax.swing.JInternalFrame {
    private String username;
    
    private Repository<Petugas> ptgRepo = new PetugasRepository();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    /**
     * Creates new form TambahBuku
     */
    public TambahPetugas() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);
        
        jam();
        customJDateChooser();
    }
    
    public void setUsername(String username) {
        this.username = username;
        String result = username.substring(0, 1).toUpperCase() + username.substring(1);
        tUserLogin.setText("Selamat Datang " + result + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        btnReset = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        tKalender = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        tNama.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tNama.setBorder(null);
        getContentPane().add(tNama);
        tNama.setBounds(470, 195, 770, 35);

        tEmail.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tEmail.setBorder(null);
        getContentPane().add(tEmail);
        tEmail.setBounds(470, 276, 770, 35);

        tUsername.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUsername.setBorder(null);
        getContentPane().add(tUsername);
        tUsername.setBounds(470, 357, 370, 35);

        tPassword.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tPassword.setBorder(null);
        getContentPane().add(tPassword);
        tPassword.setBounds(870, 357, 370, 35);

        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(470, 520, 130, 40);

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(1110, 520, 130, 40);

        tKalender.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        getContentPane().add(tKalender);
        tKalender.setBounds(470, 438, 767, 36);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Tambah Petugas.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        Petugas petugas = new Petugas(
                tEmail.getText(), 
                tUsername.getText(), 
                tPassword.getText(), 
                tNama.getText(), 
                tKalender.getDate()
        );
        
        Set<ConstraintViolation<Petugas>> vols = ValidasiUtil.validate(petugas);
        
        if (vols.size() < 1) {
            ptgRepo.add(petugas);
            
            DaftarPetugas daftarPetugas = new DaftarPetugas();
            daftarPetugas.setUsername(username);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(daftarPetugas);
            daftarPetugas.setVisible(true);

            this.dispose();
            
            new PopupViewDataBerhasil().setVisible(true);
        } else {
            new PopupViewDataGagal().setVisible(true);
            JOptionPane.showMessageDialog(this, ValidasiUtil.getErrorsAsString(vols, "\n"));
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        tNama.setText("");
        tEmail.setText("");
        tUsername.setText("");
        tPassword.setText("");
        tKalender.setDate(null);
    }//GEN-LAST:event_btnResetMouseClicked

    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();
                    
                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);
                    
                    if (jam < 10) {
                        noljam = "0";
                    }
                    
                    if (menit < 10) {
                        nolmenit = "0";
                    }
                    
                    if (detik < 10) {
                        noldetik = "0";
                    }
                    
                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;
                    
                    tJam.setText(finalJam);
            }};
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void customJDateChooser() {
        tKalender.setDateFormatString("dd - MM - yyyy");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JTextField tEmail;
    private javax.swing.JLabel tJam;
    private com.toedter.calendar.JDateChooser tKalender;
    private javax.swing.JTextField tNama;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JLabel tUserLogin;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
