/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.layouts;

import data.BukuStatus;
import data.ComboItem;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import jakarta.validation.ConstraintViolation;
import java.util.List;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import entity.Buku;
import entity.Klasifikasi;
import entity.Penerbit;
import java.awt.Color;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import util.ValidasiUtil;
import repository.Repository;
import repository.BukuRepository;
import repository.KlasifikasiRepository;
import repository.PenerbitRepository;
import util.SearchableComboBox;
import view.popup.PopupViewDataBerhasil;
import view.popup.PopupViewDataGagal;

/**
 *
 * @author Hafidz Fadhillah
 */
public class TambahBuku extends javax.swing.JInternalFrame {

    private String username;

    private Repository<Buku> bkuRepo = new BukuRepository();
    private Repository<Penerbit> pnbtRepo = new PenerbitRepository();
    private Repository<Klasifikasi> klsfRepo = new KlasifikasiRepository();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy");

    /**
     * Creates new form TambahBuku
     */
    public TambahBuku() {
        fillComboBox();
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);

        jam();
    }

    public void setUsername(String username) {
        this.username = username;

        if (username != null) {
            username = username.trim();
            // Split the username into words
            String[] words = username.split("\\s+");
            // Get the first word
            String firstWord = words[0];
            // Capitalize the first letter of the first word
            String capitalizedFirstWord = firstWord.substring(0, 1).toUpperCase() + firstWord.substring(1);
            tUserLogin.setText("Selamat Datang " + capitalizedFirstWord + " !");
        }
    }

    private void fillComboBox() {
        ComboItem[] items;
        List<Penerbit> penerbits = pnbtRepo.get();
        List<Klasifikasi> klasifikasis = klsfRepo.get();

        items = new ComboItem[penerbits.size()];
        for (int i = 0; i < penerbits.size(); i++) {
            Penerbit penerbit = penerbits.get(i);
            items[i] = new ComboItem(penerbit.getKode_penerbit(), penerbit.getKode_penerbit() + ". " + penerbit.getPenerbit() + " - " + penerbit.getKota_penerbit() + " - " + sdf.format(penerbit.getTahun_tebit()));
        }

        penerbitInput = new SearchableComboBox(items);
        penerbitInput.setFont(new java.awt.Font("Calisto MT", 0, 16));
        penerbitInput.setBorder(null);
        penerbitInput.setBounds(448, 346, 403, 35);
        penerbitInput.setBackground(new Color(0, 0, 0, 0));

        items = new ComboItem[klasifikasis.size()];
        for (int i = 0; i < klasifikasis.size(); i++) {
            Klasifikasi klasifikasi = klasifikasis.get(i);
            items[i] = new ComboItem(klasifikasi.getId_klasifikasi(), klasifikasi.getKode_ddc() + " - " + klasifikasi.getNama_klasifikasi());
        }

        klasifikasiInput = new SearchableComboBox(items);
        klasifikasiInput.setFont(new java.awt.Font("Calisto MT", 0, 16));
        klasifikasiInput.setBorder(null);
        klasifikasiInput.setBounds(883, 346, 404, 35);
        klasifikasiInput.setBackground(new Color(0, 0, 0, 0));

        getContentPane().add(penerbitInput);
        getContentPane().add(klasifikasiInput);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tJam = new javax.swing.JLabel();
        tUserLogin = new javax.swing.JLabel();
        tISBN = new javax.swing.JTextField();
        tJudulBuku = new javax.swing.JTextField();
        tNamaPengarang = new javax.swing.JTextField();
        tSumber = new javax.swing.JTextField();
        tHalaman = new javax.swing.JTextField();
        tStatus = new javax.swing.JComboBox<>();
        tJumlah = new javax.swing.JTextField();
        tCatatan = new javax.swing.JTextField();
        btnReset = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tJam.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        getContentPane().add(tJam);
        tJam.setBounds(670, 8, 110, 40);

        tUserLogin.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tUserLogin);
        tUserLogin.setBounds(1105, 15, 200, 23);

        tISBN.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tISBN.setBorder(null);
        tISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tISBNKeyPressed(evt);
            }
        });
        getContentPane().add(tISBN);
        tISBN.setBounds(447, 183, 840, 35);

        tJudulBuku.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tJudulBuku.setBorder(null);
        getContentPane().add(tJudulBuku);
        tJudulBuku.setBounds(447, 264, 403, 35);

        tNamaPengarang.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tNamaPengarang.setBorder(null);
        getContentPane().add(tNamaPengarang);
        tNamaPengarang.setBounds(882, 264, 403, 35);

        tSumber.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tSumber.setBorder(null);
        getContentPane().add(tSumber);
        tSumber.setBounds(447, 426, 405, 35);

        tHalaman.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tHalaman.setBorder(null);
        tHalaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tHalamanKeyPressed(evt);
            }
        });
        getContentPane().add(tHalaman);
        tHalaman.setBounds(882, 426, 405, 35);

        tStatus.setBackground(new Color(0,0,0,0));
        tStatus.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Layak", "Dipinjam", "Rusak", "Hilang" }));
        tStatus.setSelectedIndex(-1);
        tStatus.setBorder(null);
        getContentPane().add(tStatus);
        tStatus.setBounds(447, 507, 404, 35);

        tJumlah.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tJumlah.setBorder(null);
        tJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tJumlahKeyPressed(evt);
            }
        });
        getContentPane().add(tJumlah);
        tJumlah.setBounds(882, 507, 404, 35);

        tCatatan.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        tCatatan.setBorder(null);
        getContentPane().add(tCatatan);
        tCatatan.setBounds(450, 595, 835, 60);

        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(443, 675, 130, 40);

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(1160, 675, 130, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/layouts/Tambah Buku.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        ComboItem pnbtItem = (ComboItem) penerbitInput.getSelectedItem();
        ComboItem kodeDDCItem = (ComboItem) klasifikasiInput.getSelectedItem();

        String catatan;
        if (tCatatan.getText().equals("")) {
            catatan = null;
        } else {
            catatan = tCatatan.getText();
        }

        Buku buku = new Buku(
                tJudulBuku.getText(),
                tNamaPengarang.getText(),
                Long.valueOf(tISBN.getText()),
                pnbtRepo.get(pnbtItem.getKey()),
                tSumber.getText(),
                Integer.valueOf(tHalaman.getText()),
                BukuStatus.valueOf(tStatus.getSelectedItem().toString()),
                Integer.valueOf(tJumlah.getText()),
                catatan,
                klsfRepo.get(kodeDDCItem.getKey())
        );

        Set<ConstraintViolation<Buku>> vols = ValidasiUtil.validate(buku);

        if (vols.size() < 1) {
            bkuRepo.add(buku);

            ManajemenBuku manajemenBuku = new ManajemenBuku();
            manajemenBuku.setUsername(username);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(manajemenBuku);
            manajemenBuku.setVisible(true);

            this.dispose();

            new PopupViewDataBerhasil().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, ValidasiUtil.getErrorsAsString(vols, "\n"));
            new PopupViewDataGagal().setVisible(true);
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        tISBN.setText("");
        tJudulBuku.setText("");
        tNamaPengarang.setText("");
        penerbitInput.setSelectedIndex(0);
        klasifikasiInput.setSelectedIndex(0);
        tSumber.setText("");
        tHalaman.setText("");
        tStatus.setSelectedIndex(-1);
        tJumlah.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    private void tISBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tISBNKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            tISBN.setEditable(false);
        } else {
            tISBN.setEditable(true);
        }
    }//GEN-LAST:event_tISBNKeyPressed

    private void tHalamanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHalamanKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            tISBN.setEditable(false);
        } else {
            tISBN.setEditable(true);
        }
    }//GEN-LAST:event_tHalamanKeyPressed

    private void tJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJumlahKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            tISBN.setEditable(false);
        } else {
            tISBN.setEditable(true);
        }
    }//GEN-LAST:event_tJumlahKeyPressed

    private void jam() {
        try {
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String finalJam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    Calendar dt = Calendar.getInstance();

                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);

                    if (jam < 10) {
                        noljam = "0";
                    }

                    if (menit < 10) {
                        nolmenit = "0";
                    }

                    if (detik < 10) {
                        noldetik = "0";
                    }

                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    finalJam = Sjam + ":" + Smenit + ":" + Sdetik;

                    tJam.setText(finalJam);
                }
            };
            new javax.swing.Timer(1000, taskPerformer).start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private javax.swing.JComboBox penerbitInput;
    private javax.swing.JComboBox klasifikasiInput;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JTextField tCatatan;
    private javax.swing.JTextField tHalaman;
    private javax.swing.JTextField tISBN;
    private javax.swing.JLabel tJam;
    private javax.swing.JTextField tJudulBuku;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNamaPengarang;
    private javax.swing.JComboBox<String> tStatus;
    private javax.swing.JTextField tSumber;
    private javax.swing.JLabel tUserLogin;
    // End of variables declaration//GEN-END:variables
}
